// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using gbat.Common;
using gbat.Demo.ConsoleApp1;

namespace gbat.Demo.ConsoleApp1.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20180610082612_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("gbat.Inventory.Repository.EF.Models.IdModel.SparePartsIdFactories", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SparePartsIndex");

                    b.Property<string>("SparePartsTypeId")
                        .HasMaxLength(10);

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.ToTable("SparePartsIdFactories");
                });

            modelBuilder.Entity("gbat.Inventory.Repository.EF.Models.InventoryAlarmInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreateTime");

                    b.Property<int>("InventoryBalance");

                    b.Property<string>("SparePartsId")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("InventoryAlarmInfo");
                });

            modelBuilder.Entity("gbat.Inventory.Repository.EF.Models.SpareParts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<string>("FactoryInfo")
                        .HasMaxLength(50);

                    b.Property<string>("InOperator")
                        .HasMaxLength(10);

                    b.Property<long>("InTime");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("MotorId")
                        .HasMaxLength(20);

                    b.Property<string>("OutOperator")
                        .HasMaxLength(10);

                    b.Property<long>("OutTime");

                    b.Property<string>("SparePartsId")
                        .HasMaxLength(20);

                    b.Property<string>("SparePartsName")
                        .HasMaxLength(20);

                    b.Property<int>("SparePartsStatus");

                    b.Property<string>("SparePartsTypeId")
                        .HasMaxLength(10);

                    b.Property<long>("UselessTime");

                    b.Property<string>("WareHousesId")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("gbat.Inventory.Repository.EF.Models.SparePartsType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreateTime");

                    b.Property<int>("InventoryAlarmLimits");

                    b.Property<string>("Name")
                        .HasMaxLength(10);

                    b.Property<string>("SparePartsTypeId")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("SparePartsType");
                });

            modelBuilder.Entity("gbat.Inventory.Repository.EF.Models.WareHouses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreateTime");

                    b.Property<string>("Keeper")
                        .HasMaxLength(10);

                    b.Property<string>("MotorTypeId")
                        .HasMaxLength(4);

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Remark")
                        .HasMaxLength(50);

                    b.Property<string>("WareHousesId")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("WareHouses");
                });
#pragma warning restore 612, 618
        }
    }
}
